macro(set_default component)
    get_target_property(oconf "raven_component_${component}" "PKG_CONFFILES")
    if(oconf)
        string(REPLACE ";" "\n" oconf "${oconf}")
        file(MAKE_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}/${component})
        file(WRITE ${CMAKE_CURRENT_BINARY_DIR}/${component}/conffiles ${oconf}\n)
    endif()

    if(CPACK_GENERATOR STREQUAL "DEB")
        get_target_property(depends "raven_component_${component}" "PKG_DEPENDS")
        if(depends)
            string(REPLACE ";" ", " CPACK_DEBIAN_PACKAGE_DEPENDS "${depends}")
        endif()

        get_target_property(replaces "raven_component_${component}" "PKG_REPLACES")
        if(replaces)
            string(REPLACE ";" ", " CPACK_DEBIAN_PACKAGE_REPLACES "${replaces}")
        endif()

        get_target_property(provides "raven_component_${component}" "PKG_PROVIDES")
        if(provides)
            string(REPLACE ";" ", " CPACK_DEBIAN_PACKAGE_PROVIDES "${provides}")
        endif()

        get_target_property(breaks "raven_component_${component}" "PKG_BREAKS")
        if(breaks)
            string(REPLACE ";" ", " CPACK_DEBIAN_PACKAGE_BREAKS "${breaks}")
        endif()

        get_target_property(conflicts "raven_component_${component}" "PKG_CONFLICTS")
        if(conflicts)
            string(REPLACE ";" ", " CPACK_DEBIAN_PACKAGE_CONFLICTS "${conflicts}")
        endif()

        get_target_property(preinst "raven_component_${component}" "PKG_PREINST")
        if(preinst)
            list(APPEND CPACK_DEBIAN_PACKAGE_CONTROL_EXTRA ${preinst})
        endif()

        get_target_property(postinst "raven_component_${component}" "PKG_POSTINST")
        if(postinst)
            list(APPEND CPACK_DEBIAN_PACKAGE_CONTROL_EXTRA ${postinst})
        endif()

        get_target_property(prerm "raven_component_${component}" "PKG_PRERM")
        if(prerm)
            list(APPEND CPACK_DEBIAN_PACKAGE_CONTROL_EXTRA ${prerm})
        endif()

        get_target_property(postrm "raven_component_${component}" "PKG_POSTRM")
        if(postrm)
            list(APPEND CPACK_DEBIAN_PACKAGE_CONTROL_EXTRA ${postrm})
        endif()

        get_target_property(templates "raven_component_${component}" "PKG_TEMPLATES")
        if(templates)
            list(APPEND CPACK_DEBIAN_PACKAGE_CONTROL_EXTRA ${templates})
        endif()

        if(oconf)
            list(APPEND CPACK_DEBIAN_PACKAGE_CONTROL_EXTRA ${oconf})
        endif()
    endif()
endmacro()
