set(CMAKE_PRODUCT_PREFIX            raven)
set(CMAKE_INCLUDE_CURRENT_DIR       ON)
set(CMAKE_POSITION_INDEPENDENT_CODE ON)
set(CMAKE_CXX_STANDARD              17)

set(SHARE_INSTALL_DIR         ${CMAKE_INSTALL_PREFIX}/share/)
set(CMAKE_INSTALL_DIR         ${SHARE_INSTALL_DIR}/cmake)
set(BIN_INSTALL_DIR           ${CMAKE_INSTALL_PREFIX}/bin/)
set(LIB_INSTALL_DIR           ${CMAKE_INSTALL_PREFIX}/lib/)
set(INCLUDE_INSTALL_DIR       ${CMAKE_INSTALL_PREFIX}/include/)
set(ARCHIVE_INSTALL_DIR       ${CMAKE_INSTALL_PREFIX}/lib/)

set(RUNTIME_PREFIX            ${CMAKE_SOURCE_DIR}/runtime/${CMAKE_BUILD_TYPE})
